development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: golite.tech.pot
  :password: goliteGolite
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: golite.tech.pot
  :password: goliteGolite
  :enable_starttls_auto: true