development:
  :address: smtp.gmail.com
  :port: 587
  domain: 'gologram.com',
  :authentication: 'plain'
  :user_name: golograam
  :password: googlegologram
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  domain: 'gologram.com',
  :authentication: 'plain'
  :user_name: golograam
  :password: googlegologram
  :enable_starttls_auto: true
