development:
  :address: smtp.gmail.com
  :port: 587
  :domain: 'gologram.com'
  :authentication: 'plain'
  :user_name: golograam
  :password: googlegologram
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: 'gologram.com'
  :authentication: 'plain'
  :user_name: golograam
  :password: googlegologram
